---
- name: Add RHPDS Sandbox Crediental to Controller
  hosts: localhost
  gather_facts: False


  tasks:
    - name: Add RHPDS AWS Creds to Controller
      ansible.tower.tower_credential:
        name: "AWS_RHPDS_API"
        organization: "{{ org }}"
        state: present
        credential_type: Amazon Web Services
        validate_certs: no
        inputs:
          username: "{{aws_access_key}}"
          password: "{{aws_access_secret}}"
